const IQ_PUZZLES = Object.freeze([
  {
    id: "sequence_odd",
    category: "sequence",
    promptKey: "puzzle.choose_next",
    display: "1 · 3 · 5 · 7 · ?",
    options: ["8", "9", "10", "11"],
    correct: 1,
  },
  {
    id: "pattern_alternate",
    category: "pattern",
    promptKey: "puzzle.choose_next",
    display: "● · ▲ · ● · ▲ · ?",
    options: ["▲", "●", "■", "◆"],
    correct: 1,
  },
  {
    id: "logic_double",
    category: "logic",
    promptKey: "puzzle.apply_rule",
    display: "2 → 4   |   3 → 6   |   5 → ?",
    options: ["7", "8", "10", "12"],
    correct: 2,
  },
  {
    id: "spatial_cardinal",
    category: "spatial",
    promptKey: "puzzle.choose_next",
    display: "↑ · → · ↓ · ?",
    options: ["↗", "←", "↙", "↑"],
    correct: 1,
  },
  {
    id: "sequence_double",
    category: "sequence",
    promptKey: "puzzle.choose_next",
    display: "2 · 4 · 8 · 16 · ?",
    options: ["18", "24", "30", "32"],
    correct: 3,
  },
  {
    id: "pattern_groups",
    category: "pattern",
    promptKey: "puzzle.choose_next",
    display: "●   |   ●●   |   ●●●   |   ?",
    options: ["●●", "●●●", "●●●●", "●●●●●"],
    correct: 2,
  },
  {
    id: "logic_sum",
    category: "logic",
    promptKey: "puzzle.find_missing",
    display: "1 + 2 = 3   |   2 + 3 = 5   |   4 + 5 = ?",
    options: ["7", "8", "9", "10"],
    correct: 2,
  },
  {
    id: "spatial_diagonal",
    category: "spatial",
    promptKey: "puzzle.choose_next",
    display: "↗ · ↘ · ↙ · ?",
    options: ["↖", "→", "↓", "↗"],
    correct: 0,
  },
  {
    id: "sequence_down",
    category: "sequence",
    promptKey: "puzzle.choose_next",
    display: "10 · 8 · 6 · 4 · ?",
    options: ["0", "1", "2", "3"],
    correct: 2,
  },
  {
    id: "pattern_repeat",
    category: "pattern",
    promptKey: "puzzle.choose_next",
    display: "■ · □ · □ · ■ · □ · □ · ?",
    options: ["■", "□", "●", "▲"],
    correct: 0,
  },
]);

window.IQ_PUZZLES = IQ_PUZZLES;
